name: 'Minecraft Beta Version Style'
description: 'Get Beta Version Style Like Minecraft Beta Version (20W41-)'
branding:
  icon: 'award'  
  color: 'green'
#inputs:
#  who-to-greet:  # id of input
#    description: 'Who to greet'
#    required: true
#    default: 'World'
outputs:
  betaversion: # id of output
    description: 'Beta Version Style Like Minecraft Beta Version'
runs:
  using: 'node14'
  main: 'index.js'
